version: 0.2
phases:
  pre_build:
    commands:
      - echo Change directory...
      - echo List directory files...
      - ls
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo List active directory...
      - ls
      - echo Build started on `date`
      - echo STATIC_FOLDER_NAME=$CODEBUILD_BUILD_NUMBER
      - STATIC_FOLDER_NAME=$CODEBUILD_BUILD_NUMBER yarn run test:unit
