pipeline_bucket_name = "subtubes-io-pipeline-artifacts"
app_name             = "subtubes-ui"
app_bucket_name      = "subtubes-io-ui"
env                  = "prod"
account_id           = "568949616117"