version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 568949616117.dkr.ecr.us-west-2.amazonaws.com
      - FETCH_REPOSITORY_URI=568949616117.dkr.ecr.us-west-2.amazonaws.com/${image_name_fetch}
      - GATEWAY_REPOSITORY_URI=568949616117.dkr.ecr.us-west-2.amazonaws.com/${image_name_gateway}
      - SSE_REPOSITORY_URI=568949616117.dkr.ecr.us-west-2.amazonaws.com/${image_name_sse}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F ":" '{print $2}')
      - echo List directory files...
      - ls
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Building $FETCH_REPOSITORY_URI:$IMAGE_TAG
      - docker build -t $FETCH_REPOSITORY_URI:latest -f docker/Dockerfile.fetch .
      - docker tag $FETCH_REPOSITORY_URI:latest $FETCH_REPOSITORY_URI:$IMAGE_TAG
      - echo Building $GATEWAY_REPOSITORY_URI:$IMAGE_TAG
      - docker build -t $GATEWAY_REPOSITORY_URI:latest  -f docker/Dockerfile.gateway .
      - docker tag $GATEWAY_REPOSITORY_URI:latest $GATEWAY_REPOSITORY_URI:$IMAGE_TAG
      - echo Building $SSE_REPOSITORY_URI:$IMAGE_TAG
      - docker build -t $SSE_REPOSITORY_URI:latest -f docker/Dockerfile.sse .
      - docker tag $SSE_REPOSITORY_URI:latest $SSE_REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the docker image ...
      - docker push $FETCH_REPOSITORY_URI:$IMAGE_TAG
      - docker push $FETCH_REPOSITORY_URI:latest
      - docker push $GATEWAY_REPOSITORY_URI:$IMAGE_TAG
      - docker push $GATEWAY_REPOSITORY_URI:latest
      - docker push $SSE_REPOSITORY_URI:$IMAGE_TAG
      - docker push $SSE_REPOSITORY_URI:latest
      - printf $FETCH_REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - printf '[ { "name":"fetch","imageUri":"%s"}]' $FETCH_REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
